### PR TITLE
Add chef-marketplace support

### PR DESCRIPTION
**Pull request by ryancragun**
Adds support for the [chef marketplace](https://github.com/chef-partners/omnibus-marketplace) addon

### CODE REVIEW

**Comment by jtimberman** [comment]
@ryancragun As a product name, should this be "Chef Marketplace" or "Marketplace"?

/cc @charlesjohnson

**Comment by ryancragun** [comment]
@jtimberman The package and documentation that exist refer to it in a few ways but mostly as 'Chef Marketplace Add-on' or the 'chef-marketplace' package, therefore 'Chef Marketplace' makes the most sense to me.  I'd be more than happy to drop 'Chef' if it's deemed a more appropriate name.

**Comment by jtimberman** [comment]
I'm down for whichever, but I think it would be best to get this finalized before we commit (pun intended). I defer to @charlesjohnson :cake:

**Comment by charlesjohnson** [comment]
chef-marketplace for the short form is fine. Chef Cloud Marketplace for long name is probably better, just so we don't accidentally camp the less-specific name if we want it for something else later.

**Pull request merged**
