### PR TITLE
Add client.d folder provisioning to chef_client resource

### PR DESCRIPTION
**Pull request by martinisoft**
### Description

This adds directory creation for the chef config `client.d` folder pattern which was [introduced by default in Chef Client 12.8](https://docs.chef.io/config_rb_client.html). I figure with Chef 14 being upon us that this is a good time as any to introduce this.

### Issues Resolved

None

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by martinisoft** [comment]
Could I get a review on this @tas50? I'd like to switch away from the chef-client cookbook and onto this one. Need this feature to continue that cause since we use custom ohai plugins.

**Comment by wrightp** [comment]
Please rebase and see if that fixes the build issues.  Looks related to the kitchen.yml file rename in master. Thanks.

**Comment by martinisoft** [comment]
> Please rebase and see if that fixes the build issues. Looks related to the kitchen.yml file rename in master. Thanks.

Re-synced and rebased. 👍

**Comment by martinisoft** [comment]
Looks like master still has a failing unrelated spec.

**Comment by wrightp** [comment]
@martinisoft Thanks. I'll take a look. At least Travis is running the correct config now.

**Comment by martinisoft** [comment]
Hoping this can get merged sometime soon. Small change and active since March.

**Pull request merged**
