### PR TITLE
Fix / Improve testing and use compat_resource

### PR DESCRIPTION
**Pull request by tas50**
1) Current test kitchen tests are broken
2) Tests should include 16.04
3) The cookbook should use compat_resource to add compatibility with Chef 12.1-12.4
4) The testing framework needs a bit of an update

### CODE REVIEW

**Comment by wrightp** [comment]
I'll pull these changes and run it with a few cookbooks. I'll also take a look at the kitchen tests.

**Comment by tas50** [comment]
Thanks @wrightp  Let me know if it needs anything else

**Comment by scotthain** [comment]
If we are explicitly not supporting debian 6/ubuntu 10.04 (which Engineering Services no longer needs, to the best of my knowledge) we should do a version bump and remove this code: https://github.com/chef-cookbooks/chef-ingredient/blob/master/libraries/helpers.rb#L304-L313

**Comment by sersut** [comment]
👍 

Can we squash commits into a single commit and use the description of the PR in that commit?

Thanks for adding this @tas50

**Comment by tas50** [comment]
@scotthain I'd support removing that code if @chef-cookbooks/engineering-services is onboard

**Comment by wrightp** [comment]
makes sense to me to remove the old os logic. I'll add that change as a separate commit after I figure out the integration tests.

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @wrightp

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by wrightp** [comment]
I've removed most of the kitchen suites. The fixture recipes need to be updated and then set up properly as suites. After reviewing the Debian 6/Ubuntu 10 logic I think it needs to stay for now. I'm ok with removing them from the tests.

Just need to run this through a few cookbooks.

**Comment by tas50** [comment]
@wrightp Any update on testing this?

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by wrightp** [comment]
Merging once travis completes. I will then create a PR to publish the latest changes to supermarket. 
Changes look benign, and all tests (integration included) pass.

**Pull request merged**
