### PR TITLE
install mixlib-install from source

### PR DESCRIPTION
**Pull request by patrick-wright**
@sersut @schisamo 

I created a separate PR for the following changes:

Replaced the hacking locally mixlib-install testing code with a more standardized approach
You can now do something like: `MIXLIB_INSTALL_GIT_REF=master kitchen t "unstable-chef-server-centos-71"` and mixlib-install will be installed from source

Added `artifactory_username` and `artfactory_password` to the chef_ingredient resource.

### CODE REVIEW

**Comment by schisamo** [comment]
:+1:

**Comment by alexpop** [comment]
:+1: from me if it counts. 
I've used it successfully today with Ubuntu 14.04.

In order to use `git_href`, I had to add `git::default` to my runlist or recipe.

I also had to make some changes to mixlib-install to support `chef-compliance` packages. PR here: https://github.com/chef/mixlib-install/pull/67

**Comment by patrick-wright** [comment]
I'm wondering if we should have the `configure_from_unstable_channel` automatically include the `git` recipe.  @sersut @schisamo thoughts?

**Comment by schisamo** [comment]
@patrick-wright IMO we should not force a `git` cookbook dependency on this cookbook. Most `chef-ingredient` end-users will not be taking advantage of the `node['chef-ingredient']['mixlib-install']['git_ref']` attribute...this will be used by Chef engineers/contributors teams during new feature development.

**Comment by patrick-wright** [comment]
:1 on git

**Comment by sersut** [comment]
I'm with @schisamo. We should not install git by default.

But other than that :+1:

**Pull request merged**
