### PR TITLE
Add guard clause for windows vs other install resources

### PR DESCRIPTION
**Pull request by scotthain**
@chef-cookbooks/engineering-services 

- needs to be updated with the new `mixlib-install` version as well...

### CODE REVIEW

**Comment by patrick-wright** [comment]
Was the previous code causing an issue?  The resources' actions are set to `nothing` and whether they get executed is determined in the `file installer_script_path` resource block.

**Comment by scotthain** [comment]
@patrick-wright so on Solaris 10 - it tries to dynamically create a powershell resource, but that doesn't map in core chef, so it blows up. I added the guard clause to make it so it doesn't dynamically create :(

**Comment by sersut** [comment]
:+1:

**Comment by patrick-wright** [comment]
gotcha!  Maybe we should just move `file installer_script_path` into the `windows?` if/else block.

```ruby
if windows?
  file installer_script_path do
    content installer.install_command
    notifies :run, "powershell_script[#{install_command_resource}]", :immediately
  end

  powershell_script install_command_resource do
    # We pass the install code directly, but still depend upon the file to
    # change before executing the install
    code installer.install_command
    action :nothing

    if new_resource.product_name == 'chef'
      # We define this resource in ChefIngredientProvider
      notifies :run, 'ruby_block[stop chef run]', :immediately
    end
  end
else
  file installer_script_path do
    content installer.install_command
    notifies :run, "execute[#{install_command_resource}]", :immediately
  end

  execute install_command_resource do
    command "sudo /bin/sh #{installer_script_path}"
    action :nothing

    if new_resource.product_name == 'chef'
      # We define this resource in ChefIngredientProvider
      notifies :run, 'ruby_block[stop chef run]', :immediately
    end
  end
end
```

**Comment by scotthain** [comment]
@patrick-wright I like that - updated to follow your suggestion

**Comment by patrick-wright** [comment]
:+1:

**Comment by schisamo** [comment]
:+1:

**Pull request merged**
