### PR TITLE
Updating tests and code so Ubuntu 10 works :(

### PR DESCRIPTION
**Pull request by scotthain**
@chef-cookbooks/engineering-services

### CODE REVIEW

**Comment by jtimberman** [comment]
:+1:

**Comment by yzl** [comment]
:+1:

**Comment by schisamo** [comment]
:+1:

**Comment by scotthain** [comment]
@schisamo @jtimberman travis is failing with:
```libraries/omnitruck_handler.rb:40:7: C: Always use raise to signal exceptions.
      fail 'Uninstalling a product is currently not supported.'
      ^^^^
50 files inspected, 1 offense detected
```

I am unsure how to resolve that, it looks like a new rule in 0.37.2 - should I disable this rule in the rubocop.yml?  If not, I'm not sure what the correct course of action would be to 'fix' it in terms of adding a `raise`

**Comment by scotthain** [comment]
Per offline conversation with @jtimberman - disabling the rule for this repo.

**Pull request merged**
