### PR TITLE
When configure_from_channel limit remote_file backups to 1.

### PR DESCRIPTION
**Pull request by stephenlauck**

### CODE REVIEW

**Comment by yzl** [comment]
👍

**Comment by schisamo** [comment]
@stephenlauck I opened an issue for the _why_ behind this fix: https://github.com/chef-cookbooks/chef-ingredient/issues/107

Do you mind amending your commit message and adding a `Fixes #107` so the fix and issue are linked?

**Comment by sersut** [comment]
👍

**Comment by scotthain** [comment]
👍 pending happy travis

**Comment by sersut** [comment]
For the curious who is wondering why this did not ship yet, we are waiting for compat_resource to be fixed so that we can run our tests 😄

**Comment by yzl** [comment]
travis is happy now!

**Pull request merged**
